### PR TITLE
Add module status methods

### PR DESCRIPTION
**Pull request by grandeljay**
Was trying to find a way to simply this. What do you think?

## Before
```
$module_is_enabled = defined('MODULE_MC_MY_FIRST_MODULE') && 'true' === MODULE_MC_MY_FIRST_MODULE;

if (!$module_is_enabled) {
    return;
};
```

## After
```php
if (!module_is_enabled('MODULE_MC_MY_FIRST_MODULE')) {
    return;
};
```

### CODE REVIEW

**Comment by RobinTheHood** [comment]
> > Maybe we can solve this without a extra file and by a kind of OOP way.
> 
> Problem is, if we want to use a class, we will have to include it (or the autoloader). And that wouldn't make things simpler than they already are.
> 
> It hurts me a little to solve it functionally but that it how a large part of modified seems to operate 😕

See my last edit of my first comment. :-) Is the same you said.

**Comment by RobinTheHood** [comment]
Or we can only improve the Module `composer/autoload` with `/includes/extra/functions/composer_autoload.php` and in the file we only do ...

```php
require_once DIR_FS_DOCUMENT_ROOT . '/vendor-no-composer/autoload.php';
```

All MMLC Module are require the `composer/autoload` MMLC-Module and after that, no other MMLC module has to include the composer file with `require_once DIR_FS_DOCUMENT_ROOT . '/vendor-no-composer/autoload.php';` anymore. 🤔

**Comment by grandeljay** [comment]
> Or we can only improve the Module [composer/autoload](https://module-loader.de/modules/composer/autoload) with /includes/extra/functions/composer_autoload.php and in this file we only do ...

That sounds amazing! Is that one of your projects too? I can't see an autoload repository in your profile so you may have to make the changes yourself.

**Comment by RobinTheHood** [comment]
> That sounds amazing! Is that one of your projects too? I can't see an autoload repository in your profile so you may have to make the changes yourself.

I have done this right now. Look at the changelog at https://module-loader.de/modules/composer/autoload/1.3.0

**Comment by grandeljay** [comment]
I guess it doesn't really matter if we do this
```php
use RobinTheHood\ModifiedStdModule\Classes\StdModule;

if (StdModule::isDisabled('MODULE_MC_MY_FIRST_MODULE')) {
    return;
};
```

or
```php
use RobinTheHood\ModifiedStdModule\Classes\StdModule;

$std_module = new StdModule('MODULE_MC_MY_FIRST_MODULE');

if ($std_module->isDisabled()) {
    return;
}
```
Right? The latter has an extra line but I feel is still better for future/other methods.

What do you prefer?

**Comment by RobinTheHood** [comment]
> I guess it doesn't really matter if we do this
> 
> ```
> use RobinTheHood\ModifiedStdModule\Classes\StdModule;
> 
> if (StdModule::isDisabled('MODULE_MC_MY_FIRST_MODULE')) {
>     return;
> };
> ```
> 
> or
> 
> ```
> use RobinTheHood\ModifiedStdModule\Classes\StdModule;
> 
> $std_module = new StdModule('MODULE_MC_MY_FIRST_MODULE');
> 
> if ($std_module->isDisabled()) {
>     return;
> }
> ```
> 
> Right? The latter has an extra line but I feel is still better for future/other methods.
> 
> What do you prefer?

I prefer the 2. one, because you can use internal in StdModule::isDisabled() the `/new_files/vendor-no-composer/robinthehood/ModifiedStdModule/Classes/Configuration.php` Class without loading der whole StdModule.

**Comment by grandeljay** [comment]
Alrighty! Please re-review.

**Pull request merged**
